#spring:
#  application:
#    name: edara
#
#  logging:
#    pattern:
#      console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
#    # level:
#    #   org:
#    #     springframework:
#    #       security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:edara-project-db}
#    username: ${DATABASE_USERNAME:root}
#    password: ${DATABASE_PASSWORD}
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        # format_sql: ${HIBERNATE_FORMAT_SQL:true}
#    # show-sql: ${JPA_SHOW_SQL:true}
#
#server:
#  port: 9090
#
